version: "3.9"

services:
  server:
    image: chat-server:0.0.1
    ports:
      - 8081:8081
    working_dir: /server
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      JWT_KEY: "${JWT_KEY}"
      CLIENT_PORT: "${CLIENT_PORT}"
  client:
    image: chat-client:0.0.1
    ports: 
      - 8080:80
    working_dir: /client
    environment:
      REACT_APP_PORT: "${REACT_APP_PORT}"