version: "3.9"

services:
  server:
    build:
      dockerfile: ./server/Dockerfile
    image: chat-server:0.0.1
    container_name: server-chatApp
    restart: always
    ports:
      - 8081:8081
    working_dir: /server
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      JWT_KEY: "${JWT_KEY}"
      CLIENT_HOST: "${CLIENT_HOST}"
      PORT: "${SERVER_PORT}"
  client:
    build:
      dockerfile: ./client/Dockerfile
    image: chat-client:0.0.1
    container_name: client-chatApp
    ports: 
      - 8080:80
    working_dir: /client
    environment:
      REACT_APP_BACKEND: "${REACT_APP_BACKEND}"
      PORT: "${PORT}"